name: Auto-Update Version

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/**'

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
        
      - name: Get commit count
        id: commit
        run: echo "count=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
        
      - name: Update version in script
        run: |
          VERSION="${{ steps.date.outputs.date }}.${{ steps.commit.outputs.count }}"
          echo "Neue Version: $VERSION"
          
          # Aktualisiere die Version im Hauptskript
          sed -i "s/\$version = \"[0-9]*\.[0-9]*\.[0-9]*\"/\$version = \"$VERSION\"/" YouTubeConverter.ps1
          
          # Prüfe, ob es Änderungen gab
          if git diff --exit-code; then
            echo "Keine Versionsänderung erforderlich"
            exit 0
          fi
          
          # Commit und push der Versionsänderung
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add YouTubeConverter.ps1
          git commit -m "Automatische Aktualisierung der Version auf $VERSION"
          git push
